import { chromium } from "playwright-core";
const S = process.env.S;
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
const errors = [];
page.on("pageerror", (e) => errors.push("pageerror: " + e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push("console: " + m.text()); });
await page.goto("http://localhost:3000", { waitUntil: "networkidle" });
await page.screenshot({ path: `${S}/v2-landing.png` });
await page.fill('input[placeholder="Your name"]', "Arjun");
await page.selectOption("select", "incident_commander");
await page.click('button:has-text("Declare")');
await page.waitForURL(/\/incident\//, { timeout: 30000 });
await page.waitForSelector('text=LIVE INCIDENT TIMELINE', { timeout: 30000 });
await page.selectOption('select:has(option:text("4× speed"))', "4");
await page.click('button:has-text("Run payment-outage demo")');
await page.waitForSelector('text=HUMAN APPROVAL REQUIRED', { timeout: 60000 });
await page.waitForTimeout(800);
await page.screenshot({ path: `${S}/v2-approval.png` });
await page.click('button:has-text("Approve as")');
await page.waitForSelector('text=Status → resolved', { timeout: 60000 });
await page.waitForTimeout(1500);
await page.screenshot({ path: `${S}/v2-resolved.png` });
await page.click('text=HYPOTHESES', { timeout: 5000 }).catch(() => {});
await page.click('a:has-text("Report")');
await page.waitForSelector('text=Decision Ledger', { timeout: 30000 });
await page.screenshot({ path: `${S}/v2-report.png`, fullPage: true });
console.log("URL", page.url());
console.log("errors:", errors.length ? errors.join("\n") : "none");
await browser.close();
