import { chromium } from "playwright-core";
const S = process.env.S;
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await page.goto("http://localhost:3000", { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
await page.screenshot({ path: `${S}/noir-hero.png` });
await page.screenshot({ path: `${S}/noir-full.png`, fullPage: true });
await page.fill('input[placeholder="YOUR NAME"]', "Arjun");
await page.click('button:has-text("DECLARE")');
await page.waitForURL(/\/incident\//, { timeout: 30000 });
await page.waitForSelector("text=LIVE INCIDENT TIMELINE", { timeout: 30000 });
await page.waitForTimeout(800);
await page.screenshot({ path: `${S}/noir-warroom.png` });
console.log("errors:", errors.length ? errors.join(" | ").slice(0, 400) : "none");
await browser.close();
