import { chromium } from "playwright-core";
const S = process.env.S;
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await page.goto("http://localhost:3000/login", { waitUntil: "networkidle" });
await page.waitForTimeout(600);
await page.screenshot({ path: `${S}/auth-login.png` });
await page.evaluate(() => { localStorage.setItem("sentinel.session", "st_testsession123"); });
await page.goto("http://localhost:3000/dashboard", { waitUntil: "networkidle" });
await page.waitForSelector("text=NEW INCIDENT", { timeout: 20000 });
await page.waitForTimeout(800);
await page.screenshot({ path: `${S}/auth-dashboard.png` });
await page.fill('input[placeholder="owner/repo"]', "vercel/next.js");
await page.click('button:has-text("DECLARE")');
await page.waitForURL(/\/incident\//, { timeout: 30000 });
await page.waitForSelector("text=RECENT CHANGES", { timeout: 30000 });
await page.screenshot({ path: `${S}/auth-warroom.png` });
console.log("errors:", errors.length ? errors.join(" | ").slice(0, 300) : "none");
await browser.close();
