import { chromium } from "playwright-core";
const S = process.env.S;
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await page.goto("http://localhost:3000", { waitUntil: "domcontentloaded" });
await page.evaluate(() => localStorage.setItem("sentinel.session", "st_testsession123"));
await page.goto("http://localhost:3000/dashboard#rooms", { waitUntil: "networkidle" });
await page.waitForSelector("text=Declare an incident", { timeout: 20000 });
await page.waitForTimeout(600);
await page.click('button:has-text("INCIDENT COMMANDER")');
await page.waitForTimeout(400);
await page.screenshot({ path: `${S}/v3-rooms-dropdown.png` });
await page.keyboard.press("Escape");
await page.click('button:has-text("INTEGRATIONS")');
await page.waitForTimeout(500);
await page.screenshot({ path: `${S}/v3-integrations.png` });
console.log("errors:", errors.length ? errors.join(" | ").slice(0, 300) : "none");
await browser.close();
