import { chromium } from "playwright-core";
const S = process.env.S;
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await page.goto("http://localhost:3000", { waitUntil: "networkidle" });
await page.fill('input[placeholder="YOUR NAME"]', "Arjun");
await page.fill('input[placeholder="owner/repo (blank = none)"]', "vercel/next.js");
await page.locator("#war-room").scrollIntoViewIfNeeded();
await page.waitForTimeout(400);
await page.screenshot({ path: `${S}/gh-landing.png` });
await page.click('button:has-text("DECLARE")');
await page.waitForURL(/\/incident\//, { timeout: 30000 });
await page.waitForSelector("text=RECENT CHANGES", { timeout: 30000 });
await page.waitForTimeout(1000);
await page.screenshot({ path: `${S}/gh-warroom.png` });
console.log("errors:", errors.length ? errors.join(" | ").slice(0, 300) : "none");
await browser.close();
