import { chromium } from "playwright-core";
const S = process.env.S;
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await page.goto("http://localhost:3000", { waitUntil: "domcontentloaded" });
await page.evaluate(() => { localStorage.setItem("sentinel.session", "st_testsession123"); localStorage.setItem("sentinel.tourDone", "1"); localStorage.setItem("sentinel.me", JSON.stringify({ uid: "vijay-dev", name: "Vijay", role: "incident_commander" })); });
await page.goto("http://localhost:3000/dashboard#rooms", { waitUntil: "networkidle" });
await page.waitForSelector("text=Declare an incident", { timeout: 30000 });
await page.fill('input[placeholder="owner/repo"]', "vercel/next.js").catch(() => {});
await page.click('button:has-text("DECLARE")');
await page.waitForURL(/\/incident\//, { timeout: 30000 });
await page.waitForSelector("text=LIVE INCIDENT TIMELINE", { timeout: 30000 });
await page.click('button:has-text("RUN PAYMENT-OUTAGE DEMO")');
await page.waitForSelector("text=HUMAN APPROVAL REQUIRED", { timeout: 120000 });
await page.waitForTimeout(500);
await page.screenshot({ path: `${S}/war3-approval.png` });
await page.click('button:has-text("Approve as"), button:has-text("APPROVE AS")');
await page.waitForTimeout(9000);
await page.click('button:has-text("SENTINEL")');
await page.waitForTimeout(400);
await page.screenshot({ path: `${S}/war3-filtered.png` });
console.log("errors:", errors.length ? errors.join(" | ").slice(0, 300) : "none");
await browser.close();
